### ISSUE TITLE
Revisit headless device selection

### ISSUE THREAD

**Issue by thegecko** [thegecko/bleat#34]
Since implementing the Web Bluetooth extensions for bleat [here](https://github.com/thegecko/bleat/blob/master/api_web-bluetooth.md#extensions), I've ben thinking about possibly implementing the headless device selection UI in a different way. I think maybe having a way of registering a developer-created UI which doesn't dirty the main specification could be a different way to go. This could be implemented in one of two ways.

1) With an event handler

``` js
// New, separate root function to register a requestDevice() scan handler
bluetooth.addScanHandler(function(scanner) {
    // This function is called whenever 'requestDevice()' is executed.
    // The scanner object looks like:
    // {
    //    scan: function to start a scan
    //    devices: [] of found devices
    //    resolve: requestDevice.Promise.resolve
    //    reject: requestDevice.Promise.reject
    // }

    // This event fires when scanner.devices are changed
    scanner.addEventListener("deviceschanged", updateUI);

    // When scanner.devices have changed
    function updateUI(device) {
        // Show UI
        scanner.devices.forEach(function(device) {
            ...
        });
    }

    // When a user chooses
    function chooseDevice(index) {
        var device = scanner.devices[index];
        scanner.resolve(device);
    }

    // Begin scan
    scanner.scan();
});
```

2) With a callback function

``` js
// New, separate root function to register a requestDevice() scan handler
bluetooth.addScanHandler(function(scanner) {
    // This function is called whenever 'requestDevice()' is executed.
    // The scanner object looks like:
    // {
    //    scan: function to start a scan
    //    onDeviceFound: function to register a device found callback
    //    resolve: requestDevice.Promise.resolve
    //    reject: requestDevice.Promise.reject
    // }

    // This function is called when a device is found
    scanner.onDeviceFound(updateUI);

    // Store devices
    var devices = [];
    function updateUI(device) {
        devices.push(device);
        // Show UI
    }

    // When a user chooses
    function chooseDevice(index) {
        var device = devices[index];
        scanner.resolve(device);
    }

    // Begin scan
    scanner.scan();
});
```

You can then use `requestDevice()` just as before:

``` js
bluetooth.requestDevice({
    ...
})
.then(device => ...
```

Either of these methods could be used to undertake eddystone scanning, too.

@mikaelkindborg, @jyasskin is this a preferable approach, or do you have any further thoughts?

**Comment by thegecko** [comment]
I've updated the Web Bluetooth extensions documentation on a branch to better outline the proposal:

https://github.com/thegecko/bleat/blob/request-handler/api_web-bluetooth.md#extensions

**Comment by thegecko** [comment]
@beaufortfrancois

**Comment by beaufortfrancois** [comment]
cc @jyasskin

**Comment by beaufortfrancois** [comment]
@thegecko For info, we are currently trying to move away from the `navigator` scope to use the Web Permissions API. See https://github.com/w3c/permissions/pull/66

**Comment by thegecko** [comment]
Thanks, I'll take a read when I find some time and revisit :)

**Comment by mikaelkindborg** [comment]
@thegecko Read the new proposal (https://github.com/thegecko/bleat/blob/request-handler/api_web-bluetooth.md#extensions). Looks like a very useful API for applications that need to scan for and select devices in a flexible way.

Reflections on comparing the new proposal to the currently implemented extensions (https://github.com/thegecko/bleat/blob/master/api_web-bluetooth.md#extensions):

* bluetooth.requestDevice() is kept clean of extensions (deviceFound callback replaced by event "addRequestHandler")
* clean device selection with context.selectDevice()
* context.selectDevice(null) instead of cancelRequest seems logical

Some thoughts/questions:

* The naming "addRequestHandler" implies the possibility to add multiple handlers. Would this be practical? (For example, what will happen when starting multiple scans, or when making multiple calls to selectDevice.)
* Also "addEventListener('onscanresultchanged'," implies it would be possible to add multiple event listeners, how would this work?
* What kind of object does event parameter "e" refer to for event 'onscanresultchanged'?

Just to illustrate an alternative, here is a sketch of function "onRequestDevice" (rename of "addRequestHandler") with callback function for device found event (the callback function gets the same context object passed for convenience). Perhaps this approach is less flexible/extensible than addEventListener?

	bluetooth.onRequestDevice(context => {
		context.onScanResultChanged(context => {
			context.scanResult.some(device => {
				if (device.name === "my-sensor") {
					context.selectDevice(device);
					return true;
				}
			});
		});

		// Begin scanning
		context.scanForDevices();
	});

	bluetooth.requestDevice({
		filters:[{ services:[ "heart_rate" ] }]
	})
	.then(device => ...

**Comment by thegecko** [comment]
Scanning for beacons could be supported by implementing https://github.com/WebBluetoothCG/web-bluetooth/pull/239

**Comment by jyasskin** [comment]
It's not quite complete (it's missing a way to make `BluetoothDevice.gatt` non-null), and I haven't gone back over your API to see what I need to pull into my spec, but I hope it'll eventually serve this use case.

I guess for bleat, you can have the scan results immediately fill in `BluetoothDevice.gatt` without the extra permission request the web will need?
